### PR TITLE
Created 7x7 html table

### LINKED ISSUE #2: Create readme file with basic description of application and its functionality
## **User story**
As user, 
I want to discover information about application from this README file. It may contain  basic description of application and its functionality. 

## **Tasks**
- [ ] Create README file with basic description of application and its functionality

## **Acceptance criteria**
- [ ] User can open README file and read information about application

### LINKED ISSUE #3: Create main HTML, CSS and JS files
# User Story
As user,
I want to see empty page when I start the app (manually in live server)

# Tasks
- [ ] Create main HTML, CSS and JS files

# Acceptance criteria
- [ ] files are created and app can start (manually for now in live server)

### LINKED ISSUE #4: Create HTML table with 7x7 squares
As user,
I want to see a 7x7 table with optimal size and alignment on webpage.

### **Tasks**
- [ ]  Create 7x7 HTML table with square сells

### **Acceptance criteria**
- [ ]  Size and alignment of table must be good looking for user, it must be on one screen without scrolling

### PR DESCRIPTION
**Pull request by Ivan-Andr**
First variant of a table creared with html and css. Resolves #2, resolves #3, resolves #4

### CODE REVIEW

**Review by levnikan — DISMISSED** [review]
Good start! We might do it programmatically using js, but it's enough for now!

**Comment by levnikan** [comment]
:+1:

**Comment by Ivan-Andr** [comment]
Created  table using JS, but it has some problems with size and position on web page

**Comment by levnikan** [comment]
Generally, my recommendation is always to start with simple approach and go towards more complex one. For now let's go with the absolute sizes, it's more straightforward to understand. I've replaced relative sizing with absolute (pixels).

**Comment by levnikan** [comment]
Additionally, if you're not sure what a specific css properity does, remove it, and see what happens. If nothing, then this property is probably (not always) redundant.

**Review by levnikan — DISMISSED** [review]
Please have a look at the latest commit and locally how it looks, if you're fine, let's proceed faster. Not complicate too much.

**Review by levnikan — APPROVED** [review]

**Pull request merged**
