### PR TITLE
Issue#11 2

### PR DESCRIPTION
**Pull request by Ivan-Andr**
Another variant of app logic (stage 1,2), some bugs are still not elliminated. Problem with stage 2 currentNum calculation

### CODE REVIEW

**Comment by Ivan-Andr** [comment]
still some bugs in stage2 and strange bug in the end of stage1.

**Comment by levnikan** [comment]
we can try TDD (test driven development) approach. It might be easier to handle those functions that way. Let's make functions pure, and expect some object as their return. We could later use that object to make further actions which you are currently doing inside the function.

**Comment by levnikan** [comment]
I've done the following:
- created package.json file using `npm init`
- installed jest by `npm install --save-dev jest` https://gomakethings.com/unit-testing-with-vanilla-js/
- added .gitignore, to avoid adding node_modules folder
- adjusted scipt in package.json so that tests can be run with `npm test`

**Comment by levnikan** [comment]
I have created  `inputCheck` folder with two files, test file and normal, which might include your pure functions. I've started changing return, but did not finish, you can try to continue and maybe improve it.

**Pull request closed without merging**
